### ISSUE TITLE
Creation of objects should take a request payload rather than query params

### ISSUE THREAD

**Issue by luster** [dhvanilshah/Symmetric-Social-Network-ECE366#5]
Example: https://github.com/dhvanilshah/Symmetric-Social-Network-ECE366/blob/master/discserver/src/main/java/cool/disc/server/handler/user/UserHandlers.java#L37

It might be easier to send json from the client to the backend. Then you can use

```java
User user = objectMapper.readValue(requestContext.request().payload().get(), User.class)
```

**Comment by andyj1** [comment]
Questions:: @luster 
for unit testing, should the scope of the tested methods necessarily be public, or can be maintained private but annotated in some way for testing?

also, how would one go about testing the payload/parameter input from requestContext? we weren't sure how to use mockito to mimick requestContext for input check.

**Comment by luster** [comment]
make it package-private and you can test it. the test class should be in the same package (but in the `test` folder instead of in the `main` folder.

i.e. instead of 

```java
private Book getBook(RequestContext requestContext) {}
``` 
just do 
```java
Book getBook(RequestContext requestContext) {}
```

sometimes people will annotate these classes as `@VisibleForTesting` to prevent the IDE from telling you to make the method private. but don't worry about this.

**Comment by luster** [comment]
e.g `src/main/java/edu/cooper/bookstore/handler/BookHandler.java`

and `src/test/java/edu/cooper/bookstore/handler/BookHandlerTest.java`
