### ISSUE TITLE
For more easily testing local vs production, use .conf file to inject db url

### ISSUE THREAD

**Issue by luster** [dhvanilshah/Symmetric-Social-Network-ECE366#6]
https://github.com/dhvanilshah/Symmetric-Social-Network-ECE366/blob/master/discserver/src/main/java/cool/disc/server/store/user/UserStoreController.java#L20

If you put `mongo.url = 'srv://blahblahblah'` in the `discserver.conf` file or `discserver-user.conf` in the root of your repo, you can more easily test between a local mongo instance and your production one.

I don't know what your current one is hosted with (mongodb.net or something?), but if you're finding problems with that you should be able to install on your VM (working on having those for you tomorrow) 🙂

**Comment by andyj1** [comment]
thank you!
