### ISSUE TITLE
submodule out of date

### ISSUE THREAD

**Issue by luster** [dhvanilshah/Symmetric-Social-Network-ECE366#7]
Just be careful, when I follow through the submodule link, it takes me to an outdated git commit:

https://github.com/dhvanilshah/Symmetric-Social-Network-ECE366-Frontend/tree/f5be4f6f6779c65f57490445329ed75f0ab60c56

You can probably ditch the submodule and just clone both repos when developing. That's a fairly common practice working with both backend and frontend repo's

**Comment by ArianaFreitag** [comment]
back in date now
